# Copied from Reth's book.toml: https://github.com/paradigmxyz/reth/blob/main/book.toml

[book]
authors = ["Contower Core Contributors"]
language = "en"
multilingual = false
src = "book"
title = "Contower Book"
description = "A book on all things Contower"

[output.html]
theme = "book/theme"
git-repository-url = "https://github.com/Nodura/Contower"
default-theme = "Coal"
no-section-label = true

[output.html.fold]
enable = true
level = 1

[build]
build-dir = "target/book"

[preprocessor.template]
before = ["links"]

[preprocessor.index]

[preprocessor.links]
