[package]
name = "mev"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
ethers = { version = "2.0.2", features = ["ws"] }
ethers-flashbots = "0.13.0"
tokio = "1.27.0"
eyre = "0.6.5"
serde_json = "1.0.95"
serde = "1.0.160"
url = "2.3.1"
ethers-solc = "1.0.2"
revm = "3.0.0"
ethabi = "18.0.0"
hex = "0.4.3"
chrono = "0.4.24"
colored = "2.0.0"
tokio-uds = "0.2.7"
reqwest = "0.11.16"
libp2p = { version = "0.51.3", features = ["secp256k1", "ed25519", "tcp", "dns", "async-std", "noise", "mplex", "yamux", "websocket", "ping", "macros", "kad", "mdns", "macros", "tokio", "websocket", "gossipsub"]}
discv5 = "0.3.0"
futures = "0.3.28"
pnet = "0.33.0"
base64 = "0.21.0"
eth2_ssz = "0.4.0"
eth2_ssz_types = "0.2.1"
eth2_ssz_derive = "0.3.0"
sha2 = "0.10.6"
generic-array = "0.14.7"
slog = "2.7.0"