# Copied from Lighthouse's Cross.toml file at https://github.com/sigp/lighthouse/blob/stable/Cross.toml

[target.x86_64-unknown-linux-gnu]
pre-build = ["apt-get install -y cmake clang-3.9"]

[target.aarch64-unknown-linux-gnu]
pre-build = ["apt-get install -y cmake clang-3.9"]